import type { Metadata } from "next";
import Link from "next/link";
import { SectionHeading } from "../../components/section-heading";

export const metadata: Metadata = { title: "About", description: "The professional story behind Saroswat Roy's AI engineering, NLP research and operational technology practice.", alternates: { canonical: "/about" } };

export default function AboutPage() {
  return <div className="page-shell"><header className="page-hero"><p className="eyebrow">About</p><h1>AI engineering, grounded in how technology actually gets used.</h1><p className="lede">Saroswat Roy works at the intersection of intelligent systems and real-world technology operations, where reliability, security and human context are part of the engineering problem.</p></header>
    <section className="story-grid"><div className="story-rail"><span>2019</span><span>2023</span><span>2024</span><span>NOW</span></div><div className="story-copy"><h2>From computer science to accountable autonomy.</h2><p>Computer-science foundations led first to machine learning research and semantic analysis of code. An MSc in Artificial Intelligence at Queen Mary University of London then sharpened that direction around language: biomedical named entity recognition, transformer fine-tuning and the discipline of evaluating domain models carefully.</p><p>Applied AI work in education added a different kind of constraint. Systems had to be useful to teachers and learners while remaining age-appropriate, explainable and governed. That experience made safety a design input rather than a final compliance check.</p><p>Today, work in IT operations brings the production environment into full view: users under time pressure, device and network dependencies, security controls, service incidents and the cost of brittle automation. This is the perspective behind every featured project.</p><blockquote>Innovation is most valuable when the people relying on it can understand its boundaries and trust what happens next.</blockquote></div></section>
    <section className="section no-pad"><SectionHeading eyebrow="Working principles" title="How the work is approached." /><div className="principle-grid"><article><span>01</span><h3>Evidence before fluency</h3><p>Generated output should be grounded, cited or qualified, not trusted because it sounds certain.</p></article><article><span>02</span><h3>Autonomy with boundaries</h3><p>Agents need explicit decision rights, deterministic controls and visible escalation paths.</p></article><article><span>03</span><h3>Operations shape architecture</h3><p>Deployment, incident response, security and user support belong in early technical decisions.</p></article><article><span>04</span><h3>Explainability serves action</h3><p>An explanation is useful when it helps someone review, contest or safely continue a decision.</p></article></div></section>
    <section className="inline-cta"><h2>See these principles in working systems.</h2><Link className="button primary" href="/projects">Explore projects <span aria-hidden="true">↗</span></Link></section>
  </div>;
}
